# Generated by Django 3.2.7 on 2021-10-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='Reporting_manager',
        ),
    ]
