# Generated by Django 3.2.7 on 2021-10-18 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0002_remove_agents_reporting_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sop',
            name='Team',
        ),
        migrations.AddField(
            model_name='sop',
            name='Sop_sub_type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sop_types',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sop_types_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
