# Generated by Django 3.2.7 on 2021-10-18 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0003_auto_20211018_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop',
            name='Sop_sub_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sop_types',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_types_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
